### ISSUE TITLE
Failure updating user via Manage Users page

### ISSUE THREAD

**Issue by natecollins** [avalonmediasystem/avalon-terraform#43]
When attempting to update a user via the "Manage Users" page (e.g. https://SITENAME/persona/users/1/edit ), clicking the "Update" button results in a 500 error ("We're sorry, but something went wrong"). 

Logs report a call to a missing `update_attributes`:
```
I, [2023-07-17T23:19:53.405056 #1]  INFO -- : [8a9c7b6b-2cfa-43b5-9184-71a6062c946b] Started PUT "/persona/users/1" for 35.8.223.97 at 2023-07-17 23:19:53 +0000
I, [2023-07-17T23:19:53.409020 #1]  INFO -- : [8a9c7b6b-2cfa-43b5-9184-71a6062c946b] Processing by Samvera::Persona::UsersController#update as HTML
I, [2023-07-17T23:19:53.409117 #1]  INFO -- : [8a9c7b6b-2cfa-43b5-9184-71a6062c946b]   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"colli372@msu.edu", "username"=>"colli372@msu.edu", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Update", "id"=>"1"}
I, [2023-07-17T23:19:53.437591 #1]  INFO -- : [8a9c7b6b-2cfa-43b5-9184-71a6062c946b] Completed 500 Internal Server Error in 28ms (ActiveRecord: 4.1ms | LDP: 0.0ms | Solr: 5.3ms | Allocations: 3861)
F, [2023-07-17T23:19:53.439724 #1] FATAL -- : [8a9c7b6b-2cfa-43b5-9184-71a6062c946b]   
[8a9c7b6b-2cfa-43b5-9184-71a6062c946b] NoMethodError (undefined method `update_attributes' for #<User id: 1, username: "colli372@msu.edu", email: "colli372@msu.edu", created_at: "2023-07-17 23:09:15.310030000 +0000", updated_at: "2023-07-17 23:13:00.793982000 +0000", provider: nil, uid: "colli372@msu.edu", guest: nil, deleted_at: nil>):
[8a9c7b6b-2cfa-43b5-9184-71a6062c946b]   
[8a9c7b6b-2cfa-43b5-9184-71a6062c946b] app/controllers/samvera/persona/users_controller.rb:132:in `block in update'
[8a9c7b6b-2cfa-43b5-9184-71a6062c946b] app/controllers/samvera/persona/users_controller.rb:131:in `update'
[8a9c7b6b-2cfa-43b5-9184-71a6062c946b] config/initializers/ldp_solr_duration_logger.rb:25:in `process_action'
```

Occurred on Avalon v7.6.0 installed via an avalon-terraform deployment.

Resetting password via the "Forgot your password" email link does work as expected.

**Comment by cjcolvar** [comment]
Thanks for reporting this!  This part of the code we don't use often and was missing tests so this bug slipped through the cracks during the upgrade to Rails 7.  I wrote up a fix in https://github.com/avalonmediasystem/avalon/pull/5282 which will be in our next release.  It is also possible to turn this into a monkey-patch if you need it before then.

**Comment by natecollins** [comment]
Glad to hear you have a fix in place! No rush on patching it from our side; we're still testing Avalon and just ran across the bug is all. Thanks, Chris.
